### ISSUE TITLE
update docs about ClickHouse replication support

### ISSUE THREAD

**Issue by prashant-shahi** [SigNoz/signoz.io-old#1659]
Related:
- https://github.com/SigNoz/charts/pull/424
- https://github.com/SigNoz/charts/pull/425

Above PRs ship the support for ClickHouse cluster with multiple replicas to SIgNoz Helm chart. Previously, only multiple shards were supported.

By default, support for multiple replicas is not enabled. To enable:

```yaml
...
clickhouse:
  layout:
    replicasCount: 2
schemaMigrator:
  enableReplication: true
```

_Note: Multiple replicas increases the availability of the ClickHouse cluster however it incurs additional resource cost. **Proceed with caution!**_

---

@Calm-Rock Feel free to reach out to me, if you have any doubt on this.
