### ISSUE TITLE
Docs for using external clickhouse with SigNoz Helm chart

### ISSUE THREAD

**Issue by prashant-shahi** [SigNoz/signoz.io-old#650]
More context: https://github.com/SigNoz/charts/issues/69#issuecomment-1329633188

**Comment by RouR** [comment]
I think that `externalClickhouse` is not work.

override-values.yaml:
```

clickhouse:
  # user: null
  # password: null
  cloud: null
  enabled: false
  installCustomStorageClass: false
  secure: false
  verify: false
  persistence:
    enabled: false
  zookeeper:
    enabled: false
    
externalClickhouse:
  host: "172.16.200.10"
  # -- Name of the external cluster to run DDL queries on.
  cluster: cluster
  # -- Database name for the external cluster
  database: telemetryMetrics
  # -- Clickhouse trace database (SigNoz Traces)
  traceDatabase: telemetryTrace
  # -- User name for the external cluster to connect to the external cluster as
  user: "telemetry_user"
  # -- Password for the cluster. Ignored if existingClickhouse.existingSecret is set
  password: "telemetry_some_password_for_this_issue"
  # -- Name of an existing Kubernetes secret object containing the password
  existingSecret:
  # -- Name of the key pointing to the password in your Kubernetes secret
  existingSecretPasswordKey:
  # -- Whether to use TLS connection connecting to ClickHouse
  secure: false
  # -- Whether to verify TLS connection connecting to ClickHouse
  verify: false
  # -- HTTP port of Clickhouse
  httpPort: 8123
  # -- TCP port of Clickhouse
  tcpPort: 9000        
  
  
minio:
  enabled: false    
keycloak:
  enabled: false  
```

```
helm --namespace trace-signoze-ns template open-telemetry signoz/signoz -f override-values.yaml > 10-open-telemetry.yaml
```

```
kubectl apply -f 10-open-telemetry.yaml
```

```
kubectl -n trace-signoze-ns get pods
open-telemetry-k8s-infra-otel-agent-m48lm                   1/1     Running   0               26m
open-telemetry-k8s-infra-otel-agent-x9vkt                   1/1     Running   1 (9m10s ago)   26m
open-telemetry-k8s-infra-otel-deployment-64dc656bcf-vc728   1/1     Running   0               26m
```
Where is alertmanager, frontend, query-service?
Clickhouse databases is empty, but must init with tables.

**Comment by prashant-shahi** [comment]
@RouR You would have to keep the following value intact since they are hard-coded in query-service and OtelCollector `golang-migrate` migration files.

```
externalClickhouse:
  cluster: cluster
  database: signoz_metrics
  traceDatabase: signoz_traces
  ...
```
